const express = require('express')
const cors = require('cors')
express()
  .use(cors())
  .use(express.json())
  .use(express.urlencoded({ extended: true }))
  .use(express.static('client/build'))
	.get('/*', (req, res) => {
		let file = path.join('/app/client/build', 'index.html')
		res.sendFile(file)
	})  
  .use('/api', require('./api'))
  .listen(process.env.PORT||4000, () => console.log(`server run at http://localhost:4000`))